import { NavLink } from 'react-router-dom'
import { LayoutDashboard,Monitor,AlertTriangle,Network,Activity,History,Settings,Wifi,UserPlus,Wrench,ShieldCheck,LogOut } from 'lucide-react'
import { useAlerts } from '../../context/AlertContext'
import { useAuth } from '../../context/AuthContext'
const sections=[
 {label:'Monitor',items:[['/','Overview',LayoutDashboard],['/devices','Devices',Monitor],['/access-points','Access Points',Wifi],['/onboarding','New Devices',UserPlus],['/alerts','Alerts',AlertTriangle,true],['/topology','Network Map',Network]]},
 {label:'Review',items:[['/traffic','Traffic',Activity],['/detectors','Checks',ShieldCheck],['/history','History',History],['/troubleshooting','Troubleshooting',Wrench]]},
 {label:'System',items:[['/settings','Settings',Settings]]},
]
export default function Sidebar(){const {urgentCount}=useAlerts();const {user,logout}=useAuth();const initials=(user?.name||user?.username||'User').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();return <aside className="w-[216px] h-full bg-[var(--surface)] border-r border-[var(--border)] flex flex-col shrink-0">
 <div className="px-5 py-4 flex items-center gap-3"><div className="w-[30px] h-[30px] rounded-[7px] bg-[var(--accent)] grid place-items-center text-white font-extrabold">N</div><div><div className="text-[13px] font-bold">NetScope</div><div className="text-[10px] text-[var(--muted)] tracking-[.06em] uppercase">KNUST NOC</div></div></div>
 <nav className="flex-1 px-3 py-2 overflow-y-auto">{sections.map(s=><div key={s.label} className="mb-2"><div className="px-3 py-2 text-[10px] uppercase tracking-[.1em] text-[var(--muted)] font-semibold">{s.label}</div>{s.items.map(([to,label,Icon,badge])=><NavLink key={to} to={to} end={to==='/'} className={({isActive})=>`flex items-center gap-3 px-3 py-2 rounded text-[12px] transition-colors ${isActive?'border-l-2 border-[var(--accent)] bg-[rgba(79,124,255,.08)] text-[var(--text)] -ml-px':'text-[var(--muted)] hover:text-[var(--text)] hover:bg-white/[.025]'}`}><Icon size={15}/><span className="flex-1">{label}</span>{badge&&urgentCount>0&&<span className="min-w-[18px] h-[18px] grid place-items-center rounded-full bg-[var(--crit)] text-white text-[9px] font-bold px-1">{urgentCount}</span>}</NavLink>)}</div>)}</nav>
 <div className="px-5 py-4 border-t border-[var(--border)] flex items-center gap-3"><div className="w-[28px] h-[28px] rounded-full bg-[var(--surface2)] grid place-items-center text-[10px] font-bold text-[var(--muted)]">{initials}</div><div className="min-w-0 flex-1"><div className="text-[11px] font-medium truncate">{user?.name||user?.username}</div><div className="text-[10px] text-[var(--muted)]">{String(user?.role||'User').replaceAll('_',' ')}</div></div><button onClick={logout} title="Sign out" className="text-[var(--muted)] hover:text-[var(--text)]"><LogOut size={15}/></button></div>
 </aside>}
